services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stockshow
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.6
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    container_name: mongoUI
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
